spring:
  config:
    name: LOCAL

mandates-resolutions-ui:
  host: http://localhost:${server.port}

app:
  domain: http://192.168.10.90:8081

#Configuration flag (integration.mode) to use the mock or live integration
integration:
  mode: MOCK