server:
  port: 9999

spring:
  thymeleaf:
    suffix: .xml
    templateMode: XML
    servlet:
      content-type: text/xml

cache:
  lifespan: 21600

logging:
  level:
    root: DEBUG
  config: classpath:config/logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'

