server:
  port: 8080

spring:
  profiles:
    default: local # Default to local profile for simpler development environment set-up
  thymeleaf:
    suffix: .xml
    mode: XML
    servlet:
      content-type: text/xml

cache:
  lifespan: 21600

logging:
  level:
    root: DEBUG
  config: classpath:config/logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'

