server:
  port: 8081

spring:
  profiles:
    default: local # Default to local profile for simpler development environment set-up
    # Temporary configuration changes for your local machine go in application-local.yml
  thymeleaf:
    suffix: .xml
    mode: XML
    servlet:
      content-type: text/xml

cache:
  lifespan: 21600

logging:
  level:
    root: DEBUG
  config: classpath:config/logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
