spring:
  config:
    name: LOCAL

mandates-resolutions-ui:
  host: http://localhost:${server.port}

app:
  domain: http://host.docker.internal:${server.port}

# ---DAO base URL---
dao:
  company:
    # If UI runs on your host and DAO on your host:
    base-url: http://localhost:8083

predictive:
  companyReg:
    maxResults: 3        # how many suggestions to return
    cacheSeconds: 300     # cache /api/company/all results for 5 minutes