spring:
  config:
    name: LOCAL
  servlet:
    multipart:
          max-file-size: 10MB
          max-request-size: 10MB

mandates-resolutions-ui:
  host: http://localhost:${server.port}

app:
  domain: http://host.docker.internal:${server.port}

# ---DAO base URL---
dao:
  company:
    # If UI runs on your host and DAO on your host:
    base-url: http://localhost:8083

# --- DAO base URL the UI uses ---
mandates-resolutions-dao: http://localhost:8083

tts:
  dms:
    base-url: http://localhost:8084/api/v1/documents

predictive:
  companyReg:
    maxResults: 3        # how many suggestions to return
    cacheSeconds: 300     # cache /api/company/all results for 5 minutes